config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :business_dashes

  get 'co/index'
  get 'me/profile' => "people#show"

  devise_for :accounts
  resources :businesses do
    get 'employees'
    get 'customers'
    get 'messages'
  end

  resources :postal_addresses

  resources :people

  root 'people#index'
  
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_filter :authenticate_account!
  before_action :set_business, except: [:index, :new, :create]
  layout "co"

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def employees
    
  end

  def customers
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id] || params[:business_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:legalName, :address, :email, :faxnumber, :telephone, :taxId, :businessCategory, :faxNumber)
    end
end

app/views/businesses/_business.html.erb
<!-- A company's personal card -->
<div class="panel panel-person">
	<div class="panel-body">
		<div class="pull-left">
			<img src="http://placehold.it/80x80&text=Avatar" class="avatar">
			</div>
		<div class="pull-left person-info">
			<strong><%= @business.legalName %></strong>
			
			<br><%= @business.email %>
			<br><%= @business.telephone %><% if @business.faxNumber %>&nbsp;<%= @business.faxNumber %><% end %>
		</div>
	</div>
	<div class="panel-footer">
		<ul class="person-links text-center">
			<li><a href="#">Profile</a></li>&nbsp;|&nbsp;
			<li><a href="#">Blogs</a></li>&nbsp;|&nbsp;
			<li><a href="#">Activity</a></li>&nbsp;|&nbsp;
			<li><a href="#">Contact</a></li>
		</ul>
	</div>
</div>

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :legalName %><br>
    <%= f.text_field :legalName %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :taxId %><br>
    <%= f.text_field :taxId %>
  </div>
  <div class="field">
    <%= f.label :businessCategory %><br>
    <%= f.number_field :businessCategory %>
  </div>
  <div class="field">
    <%= f.label :faxNumber %><br>
    <%= f.text_field :faxNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/customers.html.erb
<h1>Customers</h1>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/employees.html.erb
<h1>Employees</h1>

app/views/businesses/index.html.erb
<div class="row">
<% Business.all.each do |business| %>
    <% @business = business %>
    <div class="col-md-4">
	<%= render partial: @business %>
	</div>
<% end %>
</div>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<!-- Dashboard for business -->
<h1><%= @business.legalName %>&nbsp;Dashboard</h1>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>