config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :business_dashes

  get 'co/index'
  get 'me/profile' => "people#show"

  devise_for :accounts
  resources :businesses do
    get 'employees'
    get 'customers'
    get 'messages'
  end

  resources :postal_addresses

  resources :people

  root 'people#index'
  
end

app/models/business_dash.rb
class BusinessDash < ActiveRecord::Base
  belongs_to :business
end

app/controllers/business_dashes_controller.rb
class BusinessDashesController < ApplicationController
  before_action :set_business_dash, only: [:show, :edit, :update, :destroy]
  layout "co"

  # GET /business_dashes
  # GET /business_dashes.json
  def index
    @business_dashes = BusinessDash.all
  end

  # GET /business_dashes/1
  # GET /business_dashes/1.json
  def show
  end

  # GET /business_dashes/new
  def new
    @business_dash = BusinessDash.new
  end

  # GET /business_dashes/1/edit
  def edit
  end

  # POST /business_dashes
  # POST /business_dashes.json
  def create
    @business_dash = BusinessDash.new(business_dash_params)

    respond_to do |format|
      if @business_dash.save
        format.html { redirect_to @business_dash, notice: 'Business dash was successfully created.' }
        format.json { render :show, status: :created, location: @business_dash }
      else
        format.html { render :new }
        format.json { render json: @business_dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_dashes/1
  # PATCH/PUT /business_dashes/1.json
  def update
    respond_to do |format|
      if @business_dash.update(business_dash_params)
        format.html { redirect_to @business_dash, notice: 'Business dash was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_dash }
      else
        format.html { render :edit }
        format.json { render json: @business_dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_dashes/1
  # DELETE /business_dashes/1.json
  def destroy
    @business_dash.destroy
    respond_to do |format|
      format.html { redirect_to business_dashes_url, notice: 'Business dash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_dash
      @business_dash = BusinessDash.find(params[:id])
      @business = @business_dash.business
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_dash_params
      params.require(:business_dash).permit(:title, :description, :business_id)
    end
end

app/views/business_dashes/_form.html.erb
<%= form_for(@business_dash) do |f| %>
  <% if @business_dash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_dash.errors.count, "error") %> prohibited this business_dash from being saved:</h2>

      <ul>
      <% @business_dash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="actions pull-right">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>
  <div class="clearfix"></div>
<% end %>

app/views/business_dashes/edit.html.erb
<h1><%= @business.legalName %>&nbsp;Administration</h1>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li class="active">
		<a href="#textual" role="tab" data-toggle="tab">Textual</a>
	</li>
	<li>
		<a href="#preferences" role="tab" data-toggle="tab">Preferences</a>
	</li>
	<li>
		<a href="#contact" role="tab" data-toggle="tab">Contact</a>
	</li>
	<li>
		<a href="#modules" role="tab" data-toggle="tab">Modules</a>
	</li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
	<div class="tab-pane active" id="textual">
		
		<%= render 'form' %>

	</div>
	<div class="tab-pane" id="preferences">
		...
	</div>
	<div class="tab-pane" id="contact">
		...
	</div>
	<div class="tab-pane" id="modules">
		...
	</div>
</div>

app/views/business_dashes/index.html.erb
<h1>Listing business_dashes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Business</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_dashes.each do |business_dash| %>
      <tr>
        <td><%= business_dash.title %></td>
        <td><%= business_dash.description %></td>
        <td><%= business_dash.business_id %></td>
        <td><%= link_to 'Show', business_dash %></td>
        <td><%= link_to 'Edit', edit_business_dash_path(business_dash) %></td>
        <td><%= link_to 'Destroy', business_dash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business dash', new_business_dash_path %>

app/views/business_dashes/new.html.erb
<h1>New business_dash</h1>

<%= render 'form' %>

<%= link_to 'Back', business_dashes_path %>

app/views/business_dashes/show.html.erb
<div class="row">
	<div class="col-md-12">
		<h1><%= @business_dash.title %></h1>
		<p class="lead">
			<%= @business_dash.description %>
		</p>
	</div>
	<div class="col-md-8">
		</div>
	<div class="col-md-4">
		<div class="content-container">
			<h1>Messages</h1>
			<% @business.messages.each do |message| %>
				<div class="message">
					<div class="message-heading">
						<%= message.title %>
					</div>
					<div class="message-body">
						<p><%= message.body.length > 150 ? message.body[0..150].html_safe + "&nbsp;".html_safe + link_to("Read more ...",message) : message.body.html_safe %></p>
					</div>
					<div class="message-footer">
						Posted by: <%= link_to message.author.name, message.author %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>