config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :business_dashes

  get 'co/index'
  get 'me/profile' => "people#show"

  devise_for :accounts
  resources :businesses do
    get 'employees'
    get 'customers'
    get 'messages'
  end

  resources :postal_addresses

  resources :people

  root 'people#index'
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to root_path, :class => "navbar-brand" do %><img src="/assets/img/@focus.png" height="35px" width="auto" style="padding:0;margin:0;margin-top: -10px;"/><strong>&nbsp;Framework</strong><% end %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-sitemap fa-fw"></i>&nbsp;Network <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li>
							<%= link_to :people do %>
							<i class="fa fa-child fa-fw"></i>&nbsp;Focus@Me
							<% end %>
						</li>
						<li>
							<%= link_to co_index_path do %><i class="fa fa-building fa-fw"></i>&nbsp;Focus@Co<% end %>
						</li>
						<li class="divider"></li>
						<li>
							<a href="#"><span class="text-muted"><i class="fa fa-home fa-fw"></i>&nbsp;Focus@Us <small>(Pre-Alpha)</small></span></a>
						</li>
						<li>
							<a href="#"><span class="text-muted"><i class="fa fa-mobile-phone fa-fw"></i>&nbsp;Focus@This <small>(Pre-Alpha)</small></span></a>
						</li>
					</ul>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-fw"></i>&nbsp;<%= current_account.name %><span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li class="dropdown-header"><%= current_account.email %></li>
						<li>
							<%= link_to person_path(current_account.profile) do %>
							Profile
							<% end %>
						</li>
						<li>
							<%= link_to edit_person_path(current_account.profile) do %>
							Messages
							<% end %>
						</li>
						<li>
							<%= link_to edit_person_path(current_account.profile) do %>
							Settings
							<% end %>
						</li>
						<li class="divider"></li>
						<li>
							<%= link_to destroy_account_session_path do %>Sign out<% end %>
						</li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-tabs nav-stacked" role="tablist">
  <li><%= link_to :root do %><i class="fa fa-dashboard fa-fw"></i>&nbsp;Dashboard<% end %></li>
  <li><a href="#"><i class="fa fa-user fa-fw"></i>&nbsp;Profile</a></li>
  <li><a href="#"><i class="fa fa-envelope fa-fw"></i>&nbsp;Messages</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>@Focus</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%# javascript_include_tag 'application', 'data-turbolinks-track' => false %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	</head>
	<body>
		<% if signed_in? %>
		<%= render "layouts/navbar" %>
		<div class="container">
			<div class="row">
				<div class="col-md-2">
					<%= render "layouts/sidebar" %>
				</div>
				<div class="col-md-10">
					<%= yield %>
				</div>
				<% if notice != nil && notice != "" %>
				<script><%= add_gritter(notice, :title => "Notification") %></script>
				<% end %>
				<% if alert != nil && alert != "" %>
				<script><%= add_gritter(alert, :title => "Alert") %></script>
				<% end %>
			</div>
		</div>
		<% else %>
		<%= yield %>
		<% end %>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	</body>
</html>

app/views/layouts/co.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>@Focus</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%# javascript_include_tag 'application', 'data-turbolinks-track' => false %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	</head>
	<body>
		<%= render "layouts/navbar" %>
		<div class="container">
			<div class="row">
				<div class="col-md-2">
					<%= render "business_dashes/layouts/sidebar" %>
				</div>
				<div class="col-md-10">
					<%= yield %>
				</div>
				<% if notice != nil && notice != "" %>
				<script><%= add_gritter(notice, :title => "Notification") %></script>
				<% end %>
				<% if alert != nil && alert != "" %>
				<script><%= add_gritter(alert, :title => "Alert") %></script>
				<% end %>
			</div>
		</div>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	</body>
</html>